### ISSUE TITLE
Livewire\Redirector instead of HttpFoundation\Response

### ISSUE THREAD

**Issue by Dimonka2** [livewire/livewire#1312]
Hi, I am trying to do a very basic testing with phpunit of an application: just open some random routes and the first route with Livewire gave me response 500 with following error:

`TypeError: Argument 1 passed to Illuminate\Session\Middleware\StartSession::addCookieToResponse() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Livewire\Redirector given, called in www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php on line 120 in file www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php on line 212\n`

What I have done is absolutely basic:
```php
        $response = $this->actingAs($user1)->get(route('reviewers.index'));
        // $response->dump();
        $response->assertOk();

```
The call stack is:

```
#0 www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(120): Illuminate\Session\Middleware\StartSession->addCookieToResponse(Object(Livewire\Redirector), Object(Illuminate\Session\Store))\n
#1 www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))\n
#2 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#3 www\project\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#4 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#5 www\project\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#6 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#7 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#8 www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#9 www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))\n
#10 www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))\n
#11 www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))\n
#12 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))\n
#13 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))\n
#14 www\project\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#15 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#16 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#17 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#18 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#19 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#20 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#21 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#22 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#23 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#24 www\project\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#25 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#26 www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#27 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#28 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))\n
#29 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php(507): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))\n
#30 www\project\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php(291): Illuminate\Foundation\Testing\TestCase->call('GET', 'http://localhos...', Array, Array, Array, Array)\n
#31 www\project\tests\Feature\RouteTest.php(72): Illuminate\Foundation\Testing\TestCase->get('http://localhos...')\n
#32 www\project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1415): Tests\Feature\RouteTest->test_project_routes()\n
#33 www\project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1035): PHPUnit\Framework\TestCase->runTest()\n
#34 www\project\vendor\phpunit\phpunit\src\Framework\TestResult.php(691): PHPUnit\Framework\TestCase->runBare()\n
#35 www\project\vendor\phpunit\phpunit\src\Framework\TestCase.php(763): PHPUnit\Framework\TestResult->run(Object(Tests\Feature\RouteTest))\n
#36 www\project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(597): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))\n
#37 www\project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(627): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))\n
#38 www\project\vendor\phpunit\phpunit\src\TextUI\Command.php(204): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, Array, true)\n
#39 www\project\vendor\phpunit\phpunit\src\TextUI\Command.php(163): PHPUnit\TextUI\Command->run(Array, true)\n
#40 www\project\vendor\phpunit\phpunit\phpunit(61): PHPUnit\TextUI\Command::main()\n
```

### Steps to reproduce

**Context**
- Livewire version: latest
- Laravel version: latest
- Browser: console

**Comment by Dimonka2** [comment]
Hmm, actually it is not the first one, one route with similar Livewire component did pass test without any issue.

**Comment by nuernbergerA** [comment]
`$​this​->actingAs($user1)->followingRedirectss()->get()`

Does this help?

**Comment by Dimonka2** [comment]
> Does this help?
It is really strange. The route is working for "admin" user, but fails for other users. But there is no special restrictions to this route (just to be authenticated) and it works in a web application..

**Comment by Dimonka2** [comment]
It looks like not a Livewire issue. If I test using `withoutExceptionHandling()` like this:

```php
        $user1 = $reviewer1->user;
        $this->assertNotNull($user1);
        $this->assertNotNull($user1->id);
        // var_dump($user1);
        $response = $this
            ->actingAs($user1)
            ->withoutExceptionHandling()
            ->get(route('reviewers.index'));
        // $response->dump();
        $response->assertOk();
```
Then the error is just `Illuminate\Auth\AuthenticationException: Unauthenticated.`
With a similar call stack:

```
www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php:94
www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php:55
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php:44
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:116
www\project\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:62
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103
www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:687
www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:662
www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:628
www\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:617
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:165
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:128
www\project\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php:58
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:21
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:63
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\fideloper\proxy\src\TrustProxies.php:57
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:167
www\project\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:140
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:109
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php:507
www\project\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php:291
www\project\tests\Feature\RouteTest.php:97

```

But for me it does not make sense. This user definitively exists..

**Comment by Dimonka2** [comment]
I found what was causing this error. In the App\Http\Kernel was web middleware \AuthenticateSession class enabled and in "original" Laravel git project it is disabled. I guess it was carried from past versions after upgrades.
Commenting out this middleware resolved this issue. 
I am going to close this issue.
