### ISSUE TITLE
Undefined index: fingerprint is stupidest error for ever

### ISSUE THREAD

**Issue by Hesammousavi** [livewire/livewire#1597]
in new version of livewire we can see lots of features and i thankful about your hard working.
but there is a problem that make me crazy.
and it's `Undefined index: fingerprint`
i can find this error on my logs file but i can't find where this error happend

```
[2020-09-15 10:47:30] production.ERROR: Undefined index: fingerprint {"exception":"[object] (ErrorException(code: 0): Undefined index: fingerprint at /home/roocket/vendor/livewire/livewire/src/Request.php:13)
[stacktrace]
#0 /home/roocket/vendor/livewire/livewire/src/Request.php(13): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/home/roocket/v...', 13, Array)
#1 /home/roocket/vendor/livewire/livewire/src/LifecycleManager.php(21): Livewire\\Request->__construct(Array)
#2 /home/roocket/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Livewire\\LifecycleManager::Livewire\\{closure}(Object(Livewire\\LifecycleManager))
#3 /home/roocket/vendor/livewire/livewire/src/LifecycleManager.php(23): tap(Object(Livewire\\LifecycleManager), Object(Closure))
#4 /home/roocket/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(11): Livewire\\LifecycleManager::fromSubsequentRequest(Array)
#5 /home/roocket/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(13): Livewire\\Connection\\ConnectionHandler->handle(Array)
#6 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke('comments.index')
#7 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Livewire\\Controllers\\HttpConnectionHandler), '__invoke')
#8 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#9 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#10 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/roocket/app/Http/Middleware/NoSessionForBotsMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\NoSessionForBotsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /home/roocket/app/Http/Middleware/LogLastUserActivity.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\LogLastUserActivity->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /home/roocket/app/Http/Middleware/BlockedAccount.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\BlockedAccount->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /home/roocket/app/Http/Middleware/ActiveUser.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ActiveUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/roocket/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/roocket/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/roocket/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/roocket/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#29 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/roocket/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /home/roocket/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /home/roocket/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/roocket/app/Http/Middleware/RedirectTo.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectTo->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/roocket/app/Http/Middleware/BlockInvalidIPs.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\BlockInvalidIPs->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/roocket/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home/roocket/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /home/roocket/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#54 /home/roocket/public_html/index.php(60): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#55 {main}
"} 
```
i use Defer Loading loading here 

```
<div class="comment container" id="comments-body" wire:init="loadComments">
```

and in component
```

class Index extends Component
{
    use WithPagination;

    public $readyToLoad = false;

    public $subject;
    public $pagination;

    public function mount(Model $subject , $pagination = 12)
    {
        $this->subject = $subject;
        $this->pagination = $pagination;
    }

    public function loadComments()
    {
        $this->readyToLoad = true;
    }

    public function render()
    {
        $comments =  $this->readyToLoad
            ? $this->subject->comments()
                ->where('approved' , 1)
                ->where('parent_id' , 0)
                ->latest()
                ->with('comments')
                ->paginate($this->pagination)
            : [];

        return view('livewire.comments.index' , compact('comments'));
    }
}

```

- Livewire version: 2.2.3
- Laravel version: 8.2.0

**Comment by mblarsen** [comment]
> fingerprint is stupidest error for ever

Right after this issue title haha

Jokes aside, did you figure out what the issue was?

**Comment by Hesammousavi** [comment]
@calebporzio 
i check the request wire:init
this request includes
```
{"id":"TPwmAJJs6l52aSLUpI5Q","data":{"readyToLoad":false,"subject":{"class":"App\\Episode","id":2173,"relations":["series","attachments"],"connection":"mysql"},"pagination":12,"page":1},"name":"comments.index","checksum":"395730b6344fdf76f541d0de1b9dadcef2bb77ddfc446f8247a227e87a54de1a","locale":"fa","children":{"484675779":{"id":"SoTVPkIkMVyLJXXupmxe","tag":"div"}},"actionQueue":[{"type":"callMethod","payload":{"method":"loadComments","params":[]}}]} 
```
and i think it must not be right, cuz in new version u use fingerprint in this object
i don't understand why it's happened

**Comment by Hesammousavi** [comment]
> > fingerprint is stupidest error for ever
> 
> Right after this issue title haha
> 
> Jokes aside, did you figure out what the issue was?

@mblarsen 
i closed it cuz i descided collect more info about it  ;)

**Comment by Hesammousavi** [comment]
@calebporzio need help

**Comment by calebporzio** [comment]
The HTML you've shown was generated from V1,but the Javascript is clearly V2, because it's looking for the fingerprint property.

I really don't know what would cause this. So you have any idea what would be unique about your setup that might cause this?

Like publishing new assets, but having an old livewire version or something?

**Comment by Hesammousavi** [comment]
@calebporzio 
i really can't undrestand it 

i use livewire on https://roocket.ir and a few days ago i upgraded it to v2 . in my systeam when i visit the website everything is ok and there isn't any problem but in laravel log files i received lots of logs about this error

i followed the exact steps for upgrading to v2 and I checked a few times the steps.

is it even possible that livewire.js v2 load for me and v1 load for others even with manifest.json ?

**Comment by leonardostefani** [comment]
I was facing the same issue, but I fixed it. In my case, I've added $key as property and parameter, so I've renamed it to $index, and now I'm calling in that way: 
`<livewire:foo :bar="bar" :index="$key" :key="$key">`
