### ISSUE TITLE
Livewire doesn't work with Laravel Swoole

### ISSUE THREAD

**Issue by 3tew** [livewire/livewire#2158]
### Description
Every time the input is updated (wire:model="..."), this error always occurs.
Usually, I test the project by using the command `php artisan serve` on my local machine, but when I take my project to test it again with Laravel Swoole in the Docker container, there will always be this problem.

### Stripped-down, copy-pastable code snippets
```
[2020-12-04 02:03:19] production.ERROR: Livewire encountered corrupt data when trying to hydrate the [product.create-product] component. 
Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests. {"userId":1,"exception":"[object] (Livewire\\Exceptions\\CorruptComponentPayloadException(code: 0): Livewire encountered corrupt data when trying to hydrate the [product.create-product] component. 
Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests. at /app/vendor/livewire/livewire/src/HydrationMiddleware/SecureHydrationWithChecksum.php:21)
[stacktrace]
#0 /app/vendor/livewire/livewire/src/LifecycleManager.php(70): Livewire\\HydrationMiddleware\\SecureHydrationWithChecksum::hydrate(Object(App\\Http\\Livewire\\Product\\CreateProduct), Object(Livewire\\Request))
#1 /app/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(12): Livewire\\LifecycleManager->hydrate()
#2 /app/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(13): Livewire\\Connection\\ConnectionHandler->handle(Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke('product.create-...')
#4 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Livewire\\Controllers\\HttpConnectionHandler), '__invoke')
#5 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#6 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#7 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#18 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#26 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#27 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#28 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#29 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#30 /app/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /app/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#47 /app/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(257): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#48 /app/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(217): SwooleTW\\Http\\Server\\Sandbox->handleRequest(Object(Illuminate\\Http\\Request))
#49 /app/vendor/swooletw/laravel-swoole/src/Server/Sandbox.php(179): SwooleTW\\Http\\Server\\Sandbox->prepareObResponse(Object(Illuminate\\Http\\Request))
#50 /app/vendor/swooletw/laravel-swoole/src/Server/Manager.php(225): SwooleTW\\Http\\Server\\Sandbox->run(Object(Illuminate\\Http\\Request))
#51 {main}
"} 
```

**Context**
- Livewire version: 2.3.2
- Laravel version: 8.16.1
- Alpine version: 2.7.3
- Browser: Chrome, Firefox

**Comment by austenc** [comment]
It would seem that Swoole (or the Laravel Swoole package) tampers with requests in some way that's not consistent with a request from nginx or apache. Livewire must ensure the request is not tampered with for security reasons, so it may not be possible to support this.

**Comment by tanmuhittin** [comment]
It was a long debug but I think I found the reason and a quick solution to it.

In the SecureHydrationWithChecksum method I compared the arrays fingerprint and memo using a swoole and regular server. I found that swoole server have an empty string value as NULL where it is defined as "" in regular server. If I do the checksum comparison by changing this NULL to "" it returns true

Then I debugged the request itself in the all pipeline and found that the empty string returns to NULL in TransformsRequest middleware of Laravel, which is the parent class of ConvertEmptyStringsToNull. Then I found that this middleware is not working for livewire request to livewire/message/{name} in the regular server but it works for the swoole server. This middleware is in the global middleware stack. So I taught it must be bypassed somewhere in the livewire package. Then I found it is bypassed here:

https://github.com/livewire/livewire/blob/29c74857ad8b776c3ec74ebbed3f4b835e097798/src/LivewireServiceProvider.php#L74

So, this boot method will not work in every request (because swoole already booted it and wont re-boot) and bypass wont work! Livewire also bypasses TrimStrings middleware.

As a solution,  removing ConvertEmptyStringsToNull and TrimStrings from the global $middleware array works but this middleware should work for regular endpoints. To do this go to App\Http\Kernel and follow the steps below:

- Remove ConvertEmptyStringsToNull and TrimStrings from $middleware
- Add the removed middleware ConvertEmptyStringsToNull and TrimStrings to the web middleware group
- Publish the config of livewire and change livewire.middleware_group config to livewire
- Define livewire middleware group in $middlewareGroups array. It will be the same as web middleware group but it will not have ConvertEmptyStringsToNull and TrimStrings middleware

I hope this works fine for you

**Comment by 3tew** [comment]
> It was a long debug but I think I found the reason and a quick solution to it.
> 
> In the SecureHydrationWithChecksum method I compared the arrays fingerprint and memo using a swoole and regular server. I found that swoole server have an empty string value as NULL where it is defined as "" in regular server. If I do the checksum comparison by changing this NULL to "" it returns true
> 
> Then I debugged the request itself in the all pipeline and found that the empty string returns to NULL in TransformsRequest middleware of Laravel, which is the parent class of ConvertEmptyStringsToNull. Then I found that this middleware is not working for livewire request to livewire/message/{name} in the regular server but it works for the swoole server. This middleware is in the global middleware stack. So I taught it must be bypassed somewhere in the livewire package. Then I found it is bypassed here:
> 
> https://github.com/livewire/livewire/blob/29c74857ad8b776c3ec74ebbed3f4b835e097798/src/LivewireServiceProvider.php#L74
> 
> So, this boot method will not work in every request (because swoole already booted it and wont re-boot) and bypass wont work! Livewire also bypasses TrimStrings middleware here.
> 
> As a solution, removing ConvertEmptyStringsToNull and TrimStrings from the global $middleware array works but this middlewares should work for regular endpoints. To do this go to App\Http\Kernel and follow the steps below:
> 
> * Remove ConvertEmptyStringsToNull and TrimStrings from $middleware
> * Add the removed middlewares ConvertEmptyStringsToNull and TrimStrings to the existing middleware groups (web and api as default middleware goups)
> * Publish the config of livewire and change livewire.middleware_group config to livewire
> * Define livewire middleware group in $middlewareGroups array. It will be the same as web middleware group but it will not have ConvertEmptyStringsToNull and TrimStrings middlewares
> 
> I hope this works fine for you

**It's work!** thank you very much :D

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
