### ISSUE TITLE
wire:poll not always passing through updates payload

### ISSUE THREAD

**Issue by Sn0wCrack** [livewire/livewire#2880]
### Description

I'm currently experiencing an issue with my Livewire component not always hitting the specified wire poll method.

This causes an exception to be thrown due to a local variable not being set, the component still continues to poll in the future, but it does mean it misses updating for that cycle.

This doesn't always occur, it seems to happen like once or twice in a minute.

I can see in the request data that the updates array is empty on the requests that appear to fail:

![Screen Shot 2021-05-18 at 10 31 25 am](https://user-images.githubusercontent.com/442287/118573187-65d79680-b7c5-11eb-8dba-01d367445210.png)

But is set to something like this on ones that work:

![Screen Shot 2021-05-18 at 10 40 47 am](https://user-images.githubusercontent.com/442287/118573255-87388280-b7c5-11eb-919b-c35e9319a6f5.png)

One thing about this data is that it's only pulled from cache, and this data is updated and placed in cache in the background by a Laravel Command run every 4 or so seconds by a systemd timer, I'm unsure if this would have any affect.

Previously I was doing the same here but instead of injecting a protected property into the view I used a public property, this caused issues with Livewire complaining about the checksum not matching during hydration and stopping this component from polling again.

This is the only polling component in this project that has this issue but is also the simplest in terms of how it's fetching its data, I have 5 others that do not appear to exhibit this issue, this however is the the fastest polling component, with the next fastest being every 5 seconds and the slowest being 10 minutes.

### Exact steps to reproduce

Wait for the poll to occur and keep it open for sometime, you should eventually see a HTTP 500.

### Stripped-down, copy-pastable code snippets

```php
<?php

namespace App\Http\Livewire\Dashboard;

use Illuminate\Support\Facades\Cache;
use Livewire\Component;

class PhoneQueue extends Component
{
    protected array $data;

    public function mount()
    {
        $this->fetch();
    }

    public function render()
    {
        return view('livewire.dashboard.phone-queue', [
            'data' => $this->data,
        ]);
    }

    public function fetch()
    {
        $this->data = Cache::get('phone_queue', ['agents' => [], 'queues' => [], 'cached_at' => null]);
    }
}
```

```blade
<div class="grid gap-3" wire:poll.2s.keep-alive="fetch">
  @foreach($data['queues'] as $queue)
      <div class="flex flex-row justify-between uppercase font-bold tabular-nums py-0.5">
          <span class="w-3/4:>{{ $queue['name'] }}</span>
          <span class="w-1/4 text-center">{{ $queue['wait_time'] > 0 ? seconds_to_timer($queue['wait_time']) : '' }}</span>
          <span class="w-1/4 text-center @if($queue['available_agents'] == 0) text-red-500 dark:text-red-500 @else text-green-500 dark:text-green-500 @endif">{{ $queue['available_agents'] }}</span>
          <span class="w-1/4 text-right">{{ $queue['calls_waiting'] }}</span>
      </div>
  @endforeach
</div>
```

**Context**
- Livewire version: 2.4.4
- Laravel version: 8.41.0
- Alpine version: 2.8.2
- Browser: Firefox, Chrome

**Comment by Sn0wCrack** [comment]
To further clarify this is what appears in my error log file on one of these failed requests:
```log
[2021-05-18 12:16:41] production.ERROR: Typed property App\Http\Livewire\Dashboard\PhoneQueue::$data must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property App\\Http\\Livewire\\Dashboard\\PhoneQueue::$data must not be accessed before initialization at /home/nocvent/noc-api/app/Http/Livewire/Dashboard/PhoneQueue.php:27)
[stacktrace]
#0 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\Dashboard\\PhoneQueue->render()
#1 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#3 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 /home/nocvent/noc-api/vendor/livewire/livewire/src/Component.php(121): Illuminate\\Container\\Container->call(Array)
#6 /home/nocvent/noc-api/vendor/livewire/livewire/src/LifecycleManager.php(122): Livewire\\Component->renderToView()
#7 /home/nocvent/noc-api/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->renderToView()
#8 /home/nocvent/noc-api/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle(Array)
#9 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke('dashboard.phone...')
#10 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Livewire\\Controllers\\HttpConnectionHandler), '__invoke')
#11 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#12 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#13 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#22 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/nocvent/noc-api/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/nocvent/noc-api/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /home/nocvent/noc-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 /home/nocvent/noc-api/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 {main}
"} 
```
