### ISSUE TITLE
Error when passing parameter to an action 

### ISSUE THREAD

**Issue by kriskornel** [livewire/livewire#332]
**Describe the bug**
Hi master caleb what an awesome framework, i installed livewire on laravel 5.6 and i got a problem when trying to add parameter to an action

**Error**
The message error that i got
```
[2019-10-14 11:20:58] local.ERROR: Class roomId does not exist {"userId":57,"email":"xxx@gmail.com","exception":"[object] (ReflectionException(code: -1): Class roomId does not exist at /Users/home/code/vendor/laravel/framework/src/Illuminate/Container/Container.php:767)
[stacktrace]
#0 /Users/home/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('roomId')
#1 /Users/home/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('roomId')
#2 /Users/home/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('roomId', Array)
#3 /Users/home/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\\Container\\Container->make('roomId', Array)
#4 /Users/home/code/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('roomId', Array)
```
**To Reproduce**
My Livewire component
```
class Chat extends Component
{
    public $roomId;
    public function letsTalk($roomId)
    {
        $this->roomId = $roomId;
    }
    ...
}
```

**Desktop:**
 - Browser [chrome]

**Comment by calebporzio** [comment]
Heh, thanks.

Can you post the code where you call "letsTalk"? Reason: it's possible this is happening  because you aren't passing the "roomId" properly? The issue is that Livewire is trying to resolve that param as a dependancy out of Laravel's IoC container, which tells me it was never passed into begin with.

**Comment by kriskornel** [comment]
Hi thanks for the response, 
here is my component class code
```
class Chat extends Component
{
    public $page;
    public $roomId;
    public $title;
    
    public function mount()
    {
        $this->page = 'rooms';
    }

    public function listeners()
    {
        return ['talk' => 'letsTalk'];
    }

    public function letsTalk($roomId)
    {
        $this->roomId = $roomId;
     }
}
```
And the blade file is like this
```
@forelse($rooms as $room)    
    <li class="chat-user-list clearfix">
        <a wire:click="$emit('talk', '{{ $room['uuid'] }}')">
        <span class="thumbnail-wrapper d32 circular bg-success">
  ...
@empty
 ...
@endforelse
```
When i try to use ***$emit*** function in fresh laravel 5.8 all is working good, but when i did implement in my code that use laravel 5.6, i got this kind of problem

**Comment by calebporzio** [comment]
Re-open if you are still experiencing this issue. Thanks.
