### ISSUE TITLE
Testing - passing data for mount() as of v1.0?

### ISSUE THREAD

**Issue by ohnotnow** [livewire/livewire#649]
**Describe the bug**
When testing a component that expects a model in it's mount method until 0.7.4 we would do something like :
```php
Livewire::test(MyComponent::class, $user)
```
But now that gives `ErrorException: Only arrays and Traversables can be unpacked`.  So I tried making the syntax more like the v1 @livewire with :
```php
Livewire::test(MyComponent::class, ['user' => $user])
```
Which in turn gives `ErrorException: Cannot unpack array with string keys`.  I've tried variations of the syntax, calling `->toArray()` on the model etc, but can't seem to make it happy.

**To Reproduce**
^ As above

**Expected behavior**
To be able to pass a model (or array version of it) to the component.

**Comment by LewisScottDiamond** [comment]
:pensive:

**Comment by LewisScottDiamond** [comment]
I'm sure caleb will be quick to fix it

**Comment by mikebronner** [comment]
Having the same issue. Here is the line: https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L107

And here the stack trace:
```
[previous exception] [object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot unpack array with string keys at /home/vagrant/Sites/geneamatic.com/vendor/livewire/livewire/src/LivewireManager.php:107)
[stacktrace]
#0 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Livewire\\LivewireManager->mount()
#1 /home/vagrant/Sites/geneamatic.com/storage/framework/views/f808f12b53fbf8046f2ffab24ea629504be4308b.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic()
#2 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/vagrant/S...')
#3 /home/vagrant/Sites/geneamatic.com/vendor/livewire/livewire/src/LivewireViewCompilerEngine.php(36): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#4 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#5 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\\View\\Engines\\CompilerEngine->get()
#6 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\\View\\View->getContents()
#7 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#8 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#9 /home/vagrant/Sites/geneamatic.com/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent()
#10 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\\Component\\HttpFoundation\\Response->__construct()
#11 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Router::toResponse()
#12 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Router->prepareResponse()
#13 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /home/vagrant/Sites/geneamatic.com/app/Http/Middleware/CheckProfile.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckProfile->handle()
#16 /home/vagrant/Sites/geneamatic.com/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#18 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#20 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#22 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#34 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#36 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#37 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#38 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 /home/vagrant/Sites/geneamatic.com/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#41 /home/vagrant/Sites/geneamatic.com/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): GeneaLabs\\LaravelCaffeine\\Http\\Middleware\\LaravelCaffeineDripMiddleware->handle()
#43 /home/vagrant/Sites/geneamatic.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#45 /home/vagrant/Sites/laravel-casts/src/Http/Middleware/AssetInjection.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): GeneaLabs\\LaravelCasts\\Http\\Middleware\\AssetInjection->handle()
#47 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#55 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#57 /home/vagrant/Sites/geneamatic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#58 /home/vagrant/Sites/geneamatic.com/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#59 {main}
"} 
```

**Comment by AEK-BKF** [comment]
Same error here with the latest version !
I just passed q $user object, I got that error :
`Cannot unpack array with string keys`

**Comment by SabatinoMasala** [comment]
This issue occurs when there is no `mount` method present on your component.

The reason this happens is that `resolveClassMethodDependencies` is unable to resolve to an instance method (`mount` in this case), and then returns the `$parameters`: https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L103
https://github.com/livewire/livewire/blob/master/src/DependencyResolverTrait.php#L15

Because `$parameters` is an associative array, the splat operator throws an exception, because it does not work with associative arrays:
https://github.com/livewire/livewire/blob/master/src/LivewireManager.php#L107

So a fix for this problem would be to verify you have created the `mount` method. I could provide a PR on the LiveWire side to catch this error early, if needed.

**Comment by mikebronner** [comment]
@SabatinoMasala Thanks! When I was working on this last week the documentation for the mount method hadn't been updated yet, so I wasn't sure how to implement it. Now that it's up, I tested it and it works.

**Comment by ohnotnow** [comment]
Thanks - fixed my issue too.  How I overlooked it is another matter.  I'm going to have a stern word with myself ... ;-)

**Comment by SabatinoMasala** [comment]
It is an obscure error, so I think the framework would benefit from a clearer exception.

**Comment by calebporzio** [comment]
Glad this is resolved. Closing for now. Would accept a PR for a better Exception message to prevent this in the future.

**Comment by rudyhui09** [comment]
I think this issue is coming up again. 
I try something like this:
`@livewire("admin.product.create", ["test" => "name"])`

And my Livewire component:
`public function mount($test) {
        $this->addingChild = $test;
    }`

And I get an error:
`ErrorException
Cannot unpack array with string keys`

https://flareapp.io/share/v5pgjKA7
